### ISSUE TITLE
Is MCFlux Required?

### ISSUE THREAD

**Issue by brisingraerowing** [MoSadie/ExponentialPower#10]
I get [a crash](https://gist.github.com/BrisingrAerowing/d3865664354b77d0fe2e0b8bdcfc4a09) when loading this mod in 1.11.2, stating that the IEnergy interface from MCFlux is missing. MCFlux is not listed as a dependency on Curseforge, so I wasn't aware of it being needed.

Is this intended or a bug? If it is intended, could a dependency notice be added to the Curseforge page?

**Comment by MoSadie** [comment]
Interesting... I'll have to look into this. To answer your question, MCFlux is included in the ExponentialPower jar file, so that class should be there.

**Comment by MoSadie** [comment]
Update: It appears for whatever reason that the MCFlux mod is not being packaged in. As a workaround for now, you can download the MCFlux mod via CurseForge and have that mod installed as well. I'll look into why it's not packaging it together.

**Comment by MoSadie** [comment]
I'm just going to mark MCFlux as a dependency to solve this problem. Still not sure why it's not being bundled, but it will still work. Fixed with v1.2.1.
