### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by Fortist** [MoSadie/ExponentialPower#15]
While I do like easy power, I'd like to configure how much power it gives.
Or at what rate it changes.

**Comment by thefnitalian** [comment]
I second this issue. I would like some configs to be able to make it more difficult to get those levels of power.

**Comment by MoSadie** [comment]
I think I can do that @Fortist.
In what way do you want to be able to make it more difficult @thefnitalian?

**Comment by MoSadie** [comment]
I added some configuration options in [v1.4.0](https://github.com/MoSadie/ExponentialPower/releases/tag/v1.4.0) (Also available on CurseForge). There are now config options to do these things:
* Control the base of the exponential function that calculates the energy generated by the Ender Generator. (Advanced and Regular Ender Generators can have their bases controlled separately)
* Control the amount of Ender Cells required to reach the maximum amount of energy (From 1 to 64, and again Advanced and Regular can be controlled separately)
* Control the maximum amount of power the Ender Storage can hold.

Feel free to reopen the issue if there's something you feel like I missed!

**Comment by Neb2566** [comment]
So, exponentialpower.cfg showed up in my config folder, but when I open the file there is nothing in there, its a blank page.

**Comment by MoSadie** [comment]
Hmm, that's odd, try loading a world with those blocks in it. This sounds like a bug, I'll look into it.

**Comment by MoSadie** [comment]
Closed because new issue created.

**Comment by Neb2566** [comment]
Hey, sorry I couldnt reply earlier, RL sucks :P Anyways, I'm trying to figure out this config thing but it goes right over my head. If I want my ender generator to generate a maximum of say 1000 RF/t at 64 cells, how do I go about that?

**Comment by MoSadie** [comment]
What you'll want to do is change the base config option.
For example, you want to solve the equation base^63 = 1000 (the RF/t you want)
(I would recommend using a tool like wolfram alpha to solve for it like this: http://www.wolframalpha.com/input/?i=x%5E63%3D1000 )

**Comment by Neb2566** [comment]
Thanks, that helped alot! :)
