### ISSUE TITLE
Right click functionality on ender storage block causes game to crash.

### ISSUE THREAD

**Issue by thefnitalian** [MoSadie/ExponentialPower#17]
Whenever I right click on the storage block after feeding it power from the advanced ender generator, the game crashes. I get this in the crash log:
PM
Description: Ticking player

java.lang.NoClassDefFoundError: net/darkhax/tesla/capability/TeslaCapabilities
	at io.github.mosadie.ExponentialPower.TileEntitys.EnderStorageTE.hasCapability(EnderStorageTE.java:62)
	at mrriegel.limelib.tile.IHUDProvider.isHUDProvider(IHUDProvider.java:41)
	at mrriegel.limelib.network.HUDProviderMessage.<init>(HUDProviderMessage.java:31)
	at mrriegel.limelib.util.EventHandler.playerTick(EventHandler.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_368_EventHandler_playerTick_PlayerTickEvent.invoke(.dynamic)

**Comment by MoSadie** [comment]
Thanks for the crash log! 
One question, what version of ExponentialPower is installed, and what other mods are installed? 
I'll look into it.

**Comment by thefnitalian** [comment]
The most recent version and its a custom mod pack.

**Comment by MoSadie** [comment]
Do you still have the full crash log? That would help greatly in the debugging process. You can put it in a [Gist](http://gist.github.com) or [Pastebin](https://pastebin.com/) and comment on this issue with the link.

Thanks!

**Comment by thefnitalian** [comment]
https://pastebin.com/jiqfBSu6

**Comment by MoSadie** [comment]
Thanks for posting the crash log. I've reproduced the issue so I'm now trying to see what causes that crash.

**Comment by MoSadie** [comment]
Sorry for taking so long, but the issue should be fixed in [v1.4.0](https://github.com/MoSadie/ExponentialPower/releases/tag/v1.4.0). (Also on CurseForge)
Feel free to reopen the issue if I didn't fix the issue!
