### ISSUE TITLE
Blank config file

### ISSUE THREAD

**Issue by Neb2566** [MoSadie/ExponentialPower#18]
So, just installed latest version of EP, the exponentialpower.cfg showed up in my config folder, but when I open the file its just a blank page.

**Comment by MoSadie** [comment]
Hmmm, that's odd, try creating/opening a world that has some blocks from this mod. Maybe that will help? This looks like a bug though.

**Comment by MoSadie** [comment]
The initially blank config file will be fixed in [v1.4.0.1](https://github.com/MoSadie/ExponentialPower/releases/tag/v1.4.0.1), which should be on CurseForge now.
