### ISSUE TITLE
Update to 1.16.4

### ISSUE THREAD

**Issue by lucian929** [MoSadie/ExponentialPower#19]
**What inspired you to come up with this feature?**
Me and my friends have been using this mod for 3 years and no longer want to play on 1.12.2

**What do you want me to do?**
Update the plugin to 1.16.4

**Describe alternatives you've considered**
Not using the plugin :(

**Additional context**
n/a

**Comment by MoSadie** [comment]
[v2.0.0](https://github.com/MoSadie/ExponentialPower/releases/tag/v2.0.0) :)
~~Should be up on CurseForge soon.~~ [It is live on CurseForge!](https://www.curseforge.com/minecraft/mc-mods/exponential-power/files/3514878)
