### ISSUE TITLE
Can't open the GUI of either ender generators

### ISSUE THREAD

**Issue by lucian929** [MoSadie/ExponentialPower#20]
## Description of the bug:
I can't open the GUI of the ender generator or advanced generator on the latest version (2.0.0)

## How to reproduce:
1. Open Minecraft
2. Attempt to open generator GUI

## Version information:
* Minecraft: 1.16.5
* Minecraft Forge: 36.2.8
* Exponential Power: v2.0.0

### Other mods installed
n/a

**Comment by lucian929** [comment]
by the way: thank you for updating the mod!

**Comment by MoSadie** [comment]
I can't seem to replicate this issue, just double checking there were no other mods installed right? Also if you can, the log file may be helpful.


I actually had the mod mostly updated a while ago, but it was the issue you posted that actually got me to finish the update :)

**Comment by lucian929** [comment]
Hmm, I actually did have some other mods installed, sorry for not putting that, the pack I'm using is a modified version of [ATM6](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6), is there any way for me to try diagnosing the issue without a binary search? There's over 300 mods 😅

**Comment by MoSadie** [comment]
I just tried using ATM6 with the mod added to it and it seems to work fine, a log file would be useful if you can provide one. I can search through it to see what is causing the GUI to not show up.

**Comment by lucian929** [comment]
After further testing, it works in singleplayer (with our modified version of ATM6), but not on the server. After clicking on a generator, I get this:

https://paste.gg/p/anonymous/2502dee4de5849689e28bf0ccf2c78a4

Full latest log (client):

https://paste.gg/p/anonymous/d1a0aef7d2474c57ac513c9b17817ee5 (this expires in two days)

**Comment by MoSadie** [comment]
That makes a lot more sense, it looks like the mod is attempting to load a client-only resource on the server. I can look into it further, fix should be relatively simple. If all goes well, should have a update in a few hours.

**Comment by MoSadie** [comment]
Fixed! [v2.0.1](https://github.com/MoSadie/ExponentialPower/releases/tag/v2.0.1) fixes the issue! (Also available [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/exponential-power/files/3519180) as well)

Please reopen the issue if it keeps occurring!
