### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by lucian929** [MoSadie/ExponentialPower#21]
Similar to one of my previous issues (#19), me and my friends still want to use this mod. Would love to see a 1.18.2 release!

**Comment by MoSadie** [comment]
Just published it!
Should be available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/exponential-power/files/3854786), [Modrinth](https://modrinth.com/mod/exponential-power/version/v2.1.0), and [GitHub](https://github.com/MoSadie/ExponentialPower/releases/tag/v2.1.0)
