### ISSUE TITLE
Ender Cells disappearing after X period of time

### ISSUE THREAD

**Issue by lucian929** [MoSadie/ExponentialPower#30]
## Description of the bug:
After a certain amount of time (or maybe when the chunk unloads?), the ender cells in my Advanced Ender Generator disappear.

## How to reproduce:
1. Open Minecraft & start a server
2. Craft advanced ender generator
3. Place advanced ender generator, add in ender cells (it seems the amount doesn't matter
4. Wait an unknown amount of time (30mins ish I believe), or unload the chunk (still not sure which it is), and the cell will disappear.

## Version information:
* Minecraft: 1.18.2
* Minecraft Forge: 40.1.31
* Exponential Power: 2.1.0.1

### Other mods installed
ATM 7 modpack with some modifications

**Comment by MoSadie** [comment]
Just double checking, you're using 2.1.0.1? If you are I messed up the code to save/load the nbt data of the generators (#26) in that version, I fixed the issue in 2.1.1. Give it a try and let me know if it works for you.

**Comment by lucian929** [comment]
I'll test this shortly, thanks a bunch 😄

**Comment by MoSadie** [comment]
Closing because I'm hoping everything works, please reopen if you need to!
