### ISSUE TITLE
Add the ability to generate IC2C EU energy

### ISSUE THREAD

**Issue by gfbbkon** [MoSadie/ExponentialPower#40]
Hello, I suggest you consider adding the ability to generate IC2C EU energy to your mod.

I was inspired by modifications, such as, for example, Mekanism, which could generate both RF and EU energy.

As an alternative, I can suggest a playful addition of EU energy generation.

**Comment by MoSadie** [comment]
Interesting idea, but the main problem is that the scale of the energy is different between them. 200 RF is not the same as 200 EU, and any attempt to directly convert between them would just fall apart or get complicated. If you really want this I would recommend looking for dedicated energy conversion mods. (Like [this one](https://www.curseforge.com/minecraft/mc-mods/energy-converters) I found from a quick search)

(also see IC2C's thoughts [here](https://github.com/TinyModularThings/IC2Classic/issues/856), which I agree with)
